backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
# decap astro collections config
collections:
  - name: "articles"
    label: "Articles"
    folder: "src/pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "$/layouts/Article.astro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      # - { label: "Featured Image", name: "thumbnail", widget: "image" }
      # - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }